# Generated by Django 4.2.10 on 2026-02-04 12:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('lodge', 'Lodge'), ('guesthouse', 'Guest House'), ('hotel', 'Hotel'), ('hostel', 'Hostel'), ('cabin', 'Cabin'), ('villa', 'Villa'), ('cottage', 'Cottage')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(choices=[('lusaka', 'Lusaka'), ('livingstone', 'Livingstone (Victoria Falls)'), ('ndola', 'Ndola'), ('kitwe', 'Kitwe'), ('chipata', 'Chipata'), ('kabwe', 'Kabwe'), ('mongu', 'Mongu'), ('solwezi', 'Solwezi'), ('mazabuka', 'Mazabuka')], max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('max_guests', models.PositiveIntegerField()),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('instant_book', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
